project:
  type: website
  output-dir:  docs

website:
  title: "vincentrobitaille.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Français
      - href: Anglais.qmd
        text: English

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

